/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datastrcpro;

import linkedlist.App;
import Array.Array;
import stack5.GUIStack;
import Queue.QueueGui;
import trees.TreeGUI;
import Ht.HashGUI;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import allSort.SortGui;
import heap.HeapGui;
import Graph.GraphGui;
import java.awt.Toolkit;
/**
 *
 * @author Mahmoud
 */
public class DataStrc extends javax.swing.JFrame {

    /**
     * Creates new form DataStrc
     */
    UIManager UI = new UIManager();
    
    int xMouse;
    int yMouse;
    public DataStrc() {
        setLookAndFeel();
        
        initComponents();
        setIcon();
        setLocationRelativeTo(null);
        Display.setText("Data Structures");
        MainLayer.setVisible(true);
        Displaylayer.setVisible(false);
        Back.setToolTipText("Back");
        UIManager.put("OptionPane.background", ColorUIResource.WHITE);
        UIManager.put("Panel.background", ColorUIResource.WHITE);
        
        
    }
    
    GUIStack s = new GUIStack();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainLayer = new javax.swing.JLayeredPane();
        StackBt = new javax.swing.JButton();
        LLbt = new javax.swing.JButton();
        ArraysBT = new javax.swing.JButton();
        QueueBT = new javax.swing.JButton();
        TreeBt = new javax.swing.JButton();
        Display = new javax.swing.JLabel();
        HashTableBT = new javax.swing.JButton();
        sortsBT = new javax.swing.JButton();
        heap = new javax.swing.JButton();
        graphBT = new javax.swing.JButton();
        Displaylayer = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BackGroundLayer = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        move = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Project");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        MainLayer.setMinimumSize(new java.awt.Dimension(500, 300));

        StackBt.setText("Stack");
        StackBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StackBt.setOpaque(false);
        StackBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StackBtActionPerformed(evt);
            }
        });

        LLbt.setText("Linked List");
        LLbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LLbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LLbtActionPerformed(evt);
            }
        });

        ArraysBT.setText(" Arrays");
        ArraysBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ArraysBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArraysBTActionPerformed(evt);
            }
        });

        QueueBT.setText("Queue");
        QueueBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QueueBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueueBTActionPerformed(evt);
            }
        });

        TreeBt.setText("Trees");
        TreeBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TreeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreeBtActionPerformed(evt);
            }
        });

        Display.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        Display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Display.setText("Data Structures");

        HashTableBT.setText("Hash Table");
        HashTableBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HashTableBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HashTableBTActionPerformed(evt);
            }
        });

        sortsBT.setText("Sorts");
        sortsBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortsBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortsBTActionPerformed(evt);
            }
        });

        heap.setText("Heap");
        heap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        heap.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        heap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heapActionPerformed(evt);
            }
        });

        graphBT.setText("Graph");
        graphBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        graphBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainLayerLayout = new javax.swing.GroupLayout(MainLayer);
        MainLayer.setLayout(MainLayerLayout);
        MainLayerLayout.setHorizontalGroup(
            MainLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayerLayout.createSequentialGroup()
                .addGroup(MainLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLayerLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ArraysBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(sortsBT)
                        .addGap(18, 18, 18))
                    .addGroup(MainLayerLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(LLbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(MainLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLayerLayout.createSequentialGroup()
                        .addComponent(StackBt)
                        .addGap(18, 18, 18)
                        .addComponent(QueueBT))
                    .addGroup(MainLayerLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(HashTableBT)))
                .addGroup(MainLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLayerLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(heap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TreeBt))
                    .addGroup(MainLayerLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(graphBT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(MainLayerLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(Display)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainLayerLayout.setVerticalGroup(
            MainLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayerLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(MainLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TreeBt)
                    .addComponent(ArraysBT)
                    .addComponent(sortsBT)
                    .addComponent(StackBt)
                    .addComponent(QueueBT)
                    .addComponent(heap))
                .addGap(42, 42, 42)
                .addGroup(MainLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HashTableBT)
                    .addComponent(LLbt)
                    .addComponent(graphBT))
                .addGap(149, 149, 149))
        );
        MainLayer.setLayer(StackBt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainLayer.setLayer(LLbt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainLayer.setLayer(ArraysBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainLayer.setLayer(QueueBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainLayer.setLayer(TreeBt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainLayer.setLayer(Display, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainLayer.setLayer(HashTableBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainLayer.setLayer(sortsBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainLayer.setLayer(heap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainLayer.setLayer(graphBT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(MainLayer);

        Displaylayer.setMinimumSize(new java.awt.Dimension(500, 300));

        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setOpaque(false);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datastrcpro/back-button.png"))); // NOI18N
        Back.setBorder(null);
        Back.setContentAreaFilled(false);
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(Back))
        );

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DisplaylayerLayout = new javax.swing.GroupLayout(Displaylayer);
        Displaylayer.setLayout(DisplaylayerLayout);
        DisplaylayerLayout.setHorizontalGroup(
            DisplaylayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplaylayerLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        DisplaylayerLayout.setVerticalGroup(
            DisplaylayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplaylayerLayout.createSequentialGroup()
                .addGroup(DisplaylayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DisplaylayerLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Displaylayer.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Displaylayer.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(Displaylayer);

        BackGroundLayer.setMinimumSize(new java.awt.Dimension(500, 300));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datastrcpro/close.png"))); // NOI18N
        jButton1.setToolTipText("Close");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BackGroundLayer.add(jButton1);
        jButton1.setBounds(460, 10, 30, 30);

        move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveMouseDragged(evt);
            }
        });
        move.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveMousePressed(evt);
            }
        });
        BackGroundLayer.add(move);
        move.setBounds(0, 0, 500, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datastrcpro/2514.jpg"))); // NOI18N
        BackGroundLayer.add(jLabel2);
        jLabel2.setBounds(0, 0, 510, 500);

        getContentPane().add(BackGroundLayer);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void LLbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LLbtActionPerformed
        
        App a = new App();
        jPanel2.removeAll();
        jPanel2.add(a.jLayeredPane1);
        
        MainLayer.setVisible(false);
        Displaylayer.setVisible(true);
    }//GEN-LAST:event_LLbtActionPerformed

    private void ArraysBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArraysBTActionPerformed
        Array u = new Array();
        
        jPanel2.removeAll();
        
        jPanel2.add(u.jLayeredPane1);
        
        MainLayer.setVisible(false);
        Displaylayer.setVisible(true);
    }//GEN-LAST:event_ArraysBTActionPerformed

    private void StackBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StackBtActionPerformed
        
        jPanel2.removeAll();
        
        jPanel2.add(s.sourceLayer);
        MainLayer.setVisible(false);
        Displaylayer.setVisible(true);

    }//GEN-LAST:event_StackBtActionPerformed

    private void QueueBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueueBTActionPerformed
        QueueGui q = new QueueGui();
        jPanel2.removeAll();
        jPanel2.add(q.jLayeredPane1);
        
        Displaylayer.setVisible(true);
        MainLayer.setVisible(false);

    }//GEN-LAST:event_QueueBTActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        
        if (s.StackLayer.isVisible() == true) {
            MainLayer.setVisible(true);
            Displaylayer.setVisible(false);
        }
        
        if (s.AppLayer.isVisible() == true) {
            s.AppLayer.setVisible(false);
            s.StackLayer.setVisible(true);
        }

    }//GEN-LAST:event_BackActionPerformed

    private void TreeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreeBtActionPerformed
        
        jPanel2.removeAll();
        
        jPanel2.add(new TreeGUI().Main);
        MainLayer.setVisible(false);
        Displaylayer.setVisible(true);
    }//GEN-LAST:event_TreeBtActionPerformed

    private void HashTableBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HashTableBTActionPerformed
        HashGUI h = new HashGUI();
        jPanel2.removeAll();
        jPanel2.add(h.jLayeredPane1);
        MainLayer.setVisible(false);
        Displaylayer.setVisible(true);
    }//GEN-LAST:event_HashTableBTActionPerformed

    private void sortsBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortsBTActionPerformed
        jPanel2.removeAll();
        jPanel2.add(new SortGui().jLayeredPane1);
        MainLayer.setVisible(false);
        Displaylayer.setVisible(true);
    }//GEN-LAST:event_sortsBTActionPerformed

    private void heapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heapActionPerformed
        jPanel2.removeAll();
        jPanel2.add(new HeapGui().jLayeredPane1);
        MainLayer.setVisible(false);
        Displaylayer.setVisible(true);
    }//GEN-LAST:event_heapActionPerformed

    private void graphBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphBTActionPerformed
      GraphGui gr=new GraphGui();

        jPanel2.removeAll();
       
        jPanel2.add(gr.Main);
        
        MainLayer.setVisible(false);
        Displaylayer.setVisible(true);
    }//GEN-LAST:event_graphBTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void moveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMouseDragged
       int x=evt.getXOnScreen();
       int y= evt.getYOnScreen();
       this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_moveMouseDragged

    private void moveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_moveMousePressed
    
    public void setLookAndFeel() {
        try {
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    //SwingUtilities.updateComponentTreeUI(Nim);
                    break;
                }
                
            }
            
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataStrc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DataStrc().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArraysBT;
    private javax.swing.JButton Back;
    private javax.swing.JLayeredPane BackGroundLayer;
    private javax.swing.JLabel Display;
    private javax.swing.JLayeredPane Displaylayer;
    private javax.swing.JButton HashTableBT;
    private javax.swing.JButton LLbt;
    private javax.swing.JLayeredPane MainLayer;
    private javax.swing.JButton QueueBT;
    private javax.swing.JButton StackBt;
    private javax.swing.JButton TreeBt;
    private javax.swing.JButton graphBT;
    private javax.swing.JButton heap;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JLabel move;
    private javax.swing.JButton sortsBT;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
