/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trees;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Mahmoud
 */
public class TreeGUI extends javax.swing.JFrame {

    /**
     * Creates new form TreeGUI
     */
    BinaryTree b = new BinaryTree();
    AvlTree av = new AvlTree();

    public TreeGUI() {
        setlookAndFell();
        initComponents();
        setLocationRelativeTo(null);
        type.setVisible(true);
        binary.setVisible(false);
        aVl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JLayeredPane();
        type = new javax.swing.JLayeredPane();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        aVl = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        ObSelec1AVL = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        Num1AVL = new javax.swing.JTextField();
        Name1AVL = new javax.swing.JTextField();
        InsertBTAVL = new javax.swing.JButton();
        Delete1AVL = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        display1AVL = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        binary = new javax.swing.JLayeredPane();
        InsertBT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Num = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        PostDisplay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PreDisplay = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InOrDisplay = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        Name = new javax.swing.JTextField();
        ObSelec = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);

        jButton5.setText("Binary Search Tree");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("AVL Tree");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout typeLayout = new javax.swing.GroupLayout(type);
        type.setLayout(typeLayout);
        typeLayout.setHorizontalGroup(
            typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typeLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton5)
                .addGap(67, 67, 67)
                .addComponent(jButton6)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        typeLayout.setVerticalGroup(
            typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typeLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        type.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        type.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Chosee :");

        ObSelec1AVL.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Integer", "String", "Integer and String" }));
        ObSelec1AVL.setSelectedItem(null);
        ObSelec1AVL.setName(""); // NOI18N
        ObSelec1AVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObSelec1AVLActionPerformed(evt);
            }
        });

        jLabel7.setText("Enter: ");

        InsertBTAVL.setText("Insert");
        InsertBTAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBTAVLActionPerformed(evt);
            }
        });

        Delete1AVL.setText("Delete");
        Delete1AVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete1AVLActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        display1AVL.setEditable(false);
        display1AVL.setColumns(20);
        display1AVL.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        display1AVL.setRows(5);
        jScrollPane2.setViewportView(display1AVL);

        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aVlLayout = new javax.swing.GroupLayout(aVl);
        aVl.setLayout(aVlLayout);
        aVlLayout.setHorizontalGroup(
            aVlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aVlLayout.createSequentialGroup()
                .addGroup(aVlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aVlLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(aVlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, aVlLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, aVlLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Num1AVL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Name1AVL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(InsertBTAVL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Delete1AVL))
                            .addGroup(aVlLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ObSelec1AVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(aVlLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButton7)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        aVlLayout.setVerticalGroup(
            aVlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aVlLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(aVlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ObSelec1AVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(aVlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num1AVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertBTAVL)
                    .addComponent(Delete1AVL)
                    .addComponent(jLabel7)
                    .addComponent(Name1AVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton7)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        aVl.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        aVl.setLayer(ObSelec1AVL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        aVl.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        aVl.setLayer(Num1AVL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        aVl.setLayer(Name1AVL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        aVl.setLayer(InsertBTAVL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        aVl.setLayer(Delete1AVL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        aVl.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        aVl.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        binary.setBackground(new java.awt.Color(255, 255, 255));
        binary.setForeground(new java.awt.Color(255, 255, 255));

        InsertBT.setText("Insert");
        InsertBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBTActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter: ");

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        jButton1.setText("Minimum");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Maximum");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setOpaque(false);

        PostDisplay.setEditable(false);

        jLabel2.setText("InOrder :");

        jLabel4.setText("PostOrder :");

        PreDisplay.setEditable(false);

        jLabel3.setText("Preorder :");

        InOrDisplay.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InOrDisplay)
                    .addComponent(PreDisplay)
                    .addComponent(PostDisplay)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InOrDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PreDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PostDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Is Balanced ?");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        display.setEditable(false);
        display.setColumns(20);
        display.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        ObSelec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Integer", "String", "Integer and String" }));
        ObSelec.setSelectedItem(null);
        ObSelec.setName(""); // NOI18N
        ObSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObSelecActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Chosee :");

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout binaryLayout = new javax.swing.GroupLayout(binary);
        binary.setLayout(binaryLayout);
        binaryLayout.setHorizontalGroup(
            binaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(binaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(binaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(binaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(binaryLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(binaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(binaryLayout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(clear)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4))))
                        .addGroup(binaryLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Num, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(InsertBT)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Delete)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3)))
                    .addGroup(binaryLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ObSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        binaryLayout.setVerticalGroup(
            binaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(binaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(binaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ObSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(binaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertBT)
                    .addComponent(Delete)
                    .addComponent(jLabel1)
                    .addComponent(jButton3)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(binaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(clear))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        binary.setLayer(InsertBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        binary.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        binary.setLayer(Num, javax.swing.JLayeredPane.DEFAULT_LAYER);
        binary.setLayer(Delete, javax.swing.JLayeredPane.DEFAULT_LAYER);
        binary.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        binary.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        binary.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        binary.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        binary.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        binary.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        binary.setLayer(Name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        binary.setLayer(ObSelec, javax.swing.JLayeredPane.DEFAULT_LAYER);
        binary.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        binary.setLayer(clear, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(type)
            .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(aVl))
            .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(binary))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(type)
            .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(aVl))
            .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(binary))
        );
        Main.setLayer(type, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Main.setLayer(aVl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Main.setLayer(binary, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBTActionPerformed
        if (ObSelec.getSelectedItem() == null) {

            JOptionPane.showMessageDialog(null, "Choose type first");
        }
        try {
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(0)) {
                String y = Num.getText();
                int x = Integer.parseInt(y);
                Data d = new Data(x);
                b.insert(d);
            }
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(1)) {
                String y = Name.getText();
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a Name");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y);
                    b.insert(d);
                }
            }
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(2)) {
                String y = Name.getText();
                String x = Num.getText();
                int m = Integer.parseInt(x);
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a correct Name and ID");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y, m);
                    b.insert(d);
                }
            }

            b.preOrder(b.root);
            PreDisplay.setText(b.out);
            b.out = "";

            b.postOrder(b.root);
            PostDisplay.setText(b.out);
            b.out = "";

            b.inOrder(b.root);
            InOrDisplay.setText(b.out);
            b.out = "";

            Num.setText(null);
            display.setText(b.displayTree());
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Please Enter a value ");

        }
    }//GEN-LAST:event_InsertBTActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed

        try {
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(0)) {
                String y = Num.getText();
                int x = Integer.parseInt(y);
                Data d = new Data(x);
                b.delete(d);
            }
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(1)) {
                String y = Name.getText();
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a Name");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y);
                    b.delete(d);
                }
            }
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(2)) {
                String y = Name.getText();
                String x = Num.getText();
                int m = Integer.parseInt(x);
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a correct Name and ID");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y, m);
                    b.delete(d);
                }
            }

            b.preOrder(b.root);
            PreDisplay.setText(b.out);
            b.out = "";

            b.postOrder(b.root);
            PostDisplay.setText(b.out);
            b.out = "";

            b.inOrder(b.root);
            InOrDisplay.setText(b.out);
            b.out = "";

            Num.setText(null);
        } catch (NumberFormatException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Enter a value to delete", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            JOptionPane.showMessageDialog(null, "Minimum is " + b.minimum());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No tree is there yet ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            JOptionPane.showMessageDialog(null, "Minimum is " + b.maximum());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No tree is there yet ");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (ObSelec.getSelectedItem() == ObSelec.getItemAt(0)) {
            String y = Num.getText();
            int x = Integer.parseInt(y);
            Data d = new Data(x);
            b.find(d);
        }
        if (ObSelec.getSelectedItem() == ObSelec.getItemAt(1)) {
            String y = Name.getText();
            try {
                int l = Integer.parseInt(y);
                JOptionPane.showMessageDialog(null, "Please Enter a Name");
            } catch (NumberFormatException ex) {
                Data d = new Data(y);
                b.find(d);
            }
        }
        if (ObSelec.getSelectedItem() == ObSelec.getItemAt(2)) {
            String y = Name.getText();
            String x = Num.getText();
            int m = Integer.parseInt(x);
            try {
                int l = Integer.parseInt(y);
                JOptionPane.showMessageDialog(null, "Please Enter a correct Name and ID");
            } catch (NumberFormatException ex) {
                Data d = new Data(y, m);
                b.find(d);
            }
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (b.checkBinaryTreeIsBalanced(b.root) == false) {
            JOptionPane.showMessageDialog(null, "Not Balanced");
        }
        if (b.checkBinaryTreeIsBalanced(b.root) == true) {
            JOptionPane.showMessageDialog(null, " Balanced");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void ObSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObSelecActionPerformed
        if (ObSelec.getSelectedItem() == ObSelec.getItemAt(0)) {

            Name.setEnabled(false);
            Num.setEnabled(true);
            Name.setText(null);
            Num.setText(null);
            b.clear();
            display.setText(null);
            PreDisplay.setText(null);
            PostDisplay.setText(null);
            InOrDisplay.setText(null);

        }
        if (ObSelec.getSelectedItem() == ObSelec.getItemAt(1)) {

            Num.setEnabled(false);
            Name.setEnabled(true);
            Name.setText(null);
            Num.setText(null);
            b.clear();

            display.setText(null);
            PreDisplay.setText(null);
            PostDisplay.setText(null);
            InOrDisplay.setText(null);
        }
        if (ObSelec.getSelectedItem() == ObSelec.getItemAt(2)) {

            Num.setEnabled(true);
            Name.setEnabled(true);
            Name.setText(null);
            Num.setText(null);
            b.clear();

            display.setText(null);
            PreDisplay.setText(null);
            PostDisplay.setText(null);
            InOrDisplay.setText(null);
        }
    }//GEN-LAST:event_ObSelecActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        b.clear();
        display.setText(null);
        PreDisplay.setText(null);
        PostDisplay.setText(null);
        InOrDisplay.setText(null);
    }//GEN-LAST:event_clearActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        type.setVisible(false);
        binary.setVisible(true);
        aVl.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        type.setVisible(false);
        binary.setVisible(false);
        aVl.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ObSelec1AVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObSelec1AVLActionPerformed
        if (ObSelec1AVL.getSelectedItem() == ObSelec1AVL.getItemAt(0)) {

            Name1AVL.setEnabled(false);
            Num1AVL.setEnabled(true);
            Name1AVL.setText(null);
            Num1AVL.setText(null);
            av.makeEmpty();
            display1AVL.setText(null);

        }
        if (ObSelec1AVL.getSelectedItem() == ObSelec1AVL.getItemAt(1)) {

            Num1AVL.setEnabled(false);
            Name1AVL.setEnabled(true);
            Name1AVL.setText(null);
            Num1AVL.setText(null);
            av.makeEmpty();

            display1AVL.setText(null);

        }
        if (ObSelec1AVL.getSelectedItem() == ObSelec1AVL.getItemAt(2)) {

            Num1AVL.setEnabled(true);
            Name1AVL.setEnabled(true);
            Name1AVL.setText(null);
            Num1AVL.setText(null);
            av.makeEmpty();

            display1AVL.setText(null);

        }
    }//GEN-LAST:event_ObSelec1AVLActionPerformed

    private void InsertBTAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBTAVLActionPerformed
        try {
            if (ObSelec1AVL.getSelectedItem() == ObSelec1AVL.getItemAt(0)) {
                String y = Num1AVL.getText();
                int x = Integer.parseInt(y);
                Data d = new Data(x);
                av.insert(d);
            }
            if (ObSelec1AVL.getSelectedItem() == ObSelec1AVL.getItemAt(1)) {
                String y = Name1AVL.getText();
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a Name");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y);
                    av.insert(d);
                }
            }
            if (ObSelec1AVL.getSelectedItem() == ObSelec1AVL.getItemAt(2)) {
                String y = Name1AVL.getText();
                String x = Num1AVL.getText();
                int m = Integer.parseInt(x);
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a correct Name and ID");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y, m);
                    av.insert(d);
                }
            }

            Num1AVL.setText(null);
            Name1AVL.setText(null);

            display1AVL.setText(av.displayTree());
        } catch (NumberFormatException | HeadlessException e) {

            JOptionPane.showMessageDialog(null, "Please Enter a value ");

        }
    }//GEN-LAST:event_InsertBTAVLActionPerformed

    private void Delete1AVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete1AVLActionPerformed
        try {
            if (ObSelec1AVL.getSelectedItem() == ObSelec1AVL.getItemAt(0)) {
                String y = Num1AVL.getText();
                int x = Integer.parseInt(y);
                Data d = new Data(x);
                av.remove(d);
            }
            if (ObSelec1AVL.getSelectedItem() == ObSelec1AVL.getItemAt(1)) {
                String y = Name1AVL.getText();
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a Name");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y);
                    av.remove(d);
                }
            }
            if (ObSelec1AVL.getSelectedItem() == ObSelec1AVL.getItemAt(2)) {
                String y = Name1AVL.getText();
                String x = Num1AVL.getText();
                int m = Integer.parseInt(x);
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a correct Name and ID");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y, m);
                    av.remove(d);
                }
            }

            display1AVL.setText(av.displayTree());

            Num1AVL.setText(null);
            Name1AVL.setText(null);
        } catch (NumberFormatException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Enter a value to delete", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Delete1AVLActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        av.makeEmpty();
        display1AVL.setText(null);
    }//GEN-LAST:event_jButton7ActionPerformed

    public final void setlookAndFell() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            new TreeGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Delete1AVL;
    private javax.swing.JTextField InOrDisplay;
    private javax.swing.JButton InsertBT;
    private javax.swing.JButton InsertBTAVL;
    public javax.swing.JLayeredPane Main;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Name1AVL;
    private javax.swing.JTextField Num;
    private javax.swing.JTextField Num1AVL;
    private javax.swing.JComboBox ObSelec;
    private javax.swing.JComboBox ObSelec1AVL;
    private javax.swing.JTextField PostDisplay;
    private javax.swing.JTextField PreDisplay;
    public javax.swing.JLayeredPane aVl;
    public javax.swing.JLayeredPane binary;
    private javax.swing.JButton clear;
    private javax.swing.JTextArea display;
    private javax.swing.JTextArea display1AVL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLayeredPane type;
    // End of variables declaration//GEN-END:variables
}
