/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graph;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import javax.swing.JOptionPane;

/**
 *
 * @author Mahmoud
 */
public class GraphGui extends javax.swing.JFrame {

    /**
     * Creates new form GraphGui
     */
    adjacencyMatrix m = new adjacencyMatrix();
    Dfs df = new Dfs();
    Bfs bf = new Bfs();

    int[] x = new int[df.MAX_VERTS];
    int[] y = new int[df.MAX_VERTS];
    int[] xB = new int[df.MAX_VERTS];
    int[] yB = new int[df.MAX_VERTS];
    public Graphics2D d;
    public Graphics2D doo;

    public Graphics2D dB;
    public Graphics2D dooB;
    int i = 0;
    int iB = 0;

    public GraphGui() {
        setlookAndFeel();
        initComponents();
        setLocationRelativeTo(null);

        jLayeredPane1.setVisible(true);
        adjMatrics.setVisible(false);
        dFS.setVisible(false);
        bFS.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JLayeredPane();
        bFS = new javax.swing.JLayeredPane();
        ver2bs = new javax.swing.JTextField();
        AddV2Bs = new javax.swing.JButton();
        start2Bs = new javax.swing.JTextField();
        end2Bs = new javax.swing.JTextField();
        AddE2Bs = new javax.swing.JButton();
        display1Bs = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        bfsBT = new javax.swing.JButton();
        dFS = new javax.swing.JLayeredPane();
        ver1 = new javax.swing.JTextField();
        AddV1 = new javax.swing.JButton();
        start1 = new javax.swing.JTextField();
        end1 = new javax.swing.JTextField();
        AddE1 = new javax.swing.JButton();
        display = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dFsBT = new javax.swing.JButton();
        adjMatrics = new javax.swing.JLayeredPane();
        end = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Display = new javax.swing.JTextArea();
        AddE = new javax.swing.JButton();
        ver = new javax.swing.JTextField();
        AddV = new javax.swing.JButton();
        start = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        adjMa = new javax.swing.JButton();
        bfs = new javax.swing.JButton();
        dfs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddV2Bs.setText("Add Vertex");
        AddV2Bs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddV2BsActionPerformed(evt);
            }
        });

        AddE2Bs.setText("Add Edge");
        AddE2Bs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddE2BsActionPerformed(evt);
            }
        });

        display1Bs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        display1Bs.setOpaque(false);
        display1Bs.setPreferredSize(new java.awt.Dimension(400, 207));

        javax.swing.GroupLayout display1BsLayout = new javax.swing.GroupLayout(display1Bs);
        display1Bs.setLayout(display1BsLayout);
        display1BsLayout.setHorizontalGroup(
            display1BsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );
        display1BsLayout.setVerticalGroup(
            display1BsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );

        jPanel3.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bfsBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bfsBT.setForeground(new java.awt.Color(0, 204, 204));
        bfsBT.setText("BFS");
        bfsBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfsBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bFSLayout = new javax.swing.GroupLayout(bFS);
        bFS.setLayout(bFSLayout);
        bFSLayout.setHorizontalGroup(
            bFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bFSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bFSLayout.createSequentialGroup()
                        .addComponent(ver2bs, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddV2Bs)
                        .addGap(41, 41, 41)
                        .addComponent(start2Bs, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(end2Bs, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddE2Bs))
                    .addGroup(bFSLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bfsBT, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(display1Bs, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        bFSLayout.setVerticalGroup(
            bFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bFSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddV2Bs)
                    .addComponent(ver2bs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start2Bs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(end2Bs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddE2Bs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(display1Bs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bfsBT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        bFS.setLayer(ver2bs, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bFS.setLayer(AddV2Bs, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bFS.setLayer(start2Bs, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bFS.setLayer(end2Bs, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bFS.setLayer(AddE2Bs, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bFS.setLayer(display1Bs, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bFS.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bFS.setLayer(bfsBT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        AddV1.setText("Add Vertex");
        AddV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddV1ActionPerformed(evt);
            }
        });

        AddE1.setText("Add Edge");
        AddE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddE1ActionPerformed(evt);
            }
        });

        display.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        display.setOpaque(false);
        display.setPreferredSize(new java.awt.Dimension(400, 207));

        javax.swing.GroupLayout displayLayout = new javax.swing.GroupLayout(display);
        display.setLayout(displayLayout);
        displayLayout.setHorizontalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );
        displayLayout.setVerticalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );

        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        dFsBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dFsBT.setForeground(new java.awt.Color(0, 204, 204));
        dFsBT.setText("DFS");
        dFsBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dFsBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dFSLayout = new javax.swing.GroupLayout(dFS);
        dFS.setLayout(dFSLayout);
        dFSLayout.setHorizontalGroup(
            dFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dFSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dFSLayout.createSequentialGroup()
                        .addComponent(ver1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddV1)
                        .addGap(41, 41, 41)
                        .addComponent(start1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(end1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddE1))
                    .addGroup(dFSLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dFsBT, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        dFSLayout.setVerticalGroup(
            dFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dFSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddV1)
                    .addComponent(ver1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(end1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddE1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dFsBT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        dFS.setLayer(ver1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dFS.setLayer(AddV1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dFS.setLayer(start1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dFS.setLayer(end1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dFS.setLayer(AddE1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dFS.setLayer(display, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dFS.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dFS.setLayer(dFsBT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        Display.setEditable(false);
        Display.setColumns(20);
        Display.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Display.setRows(5);
        jScrollPane1.setViewportView(Display);

        AddE.setText("Add Edge");
        AddE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEActionPerformed(evt);
            }
        });

        AddV.setText("Add Vertex");
        AddV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adjMatricsLayout = new javax.swing.GroupLayout(adjMatrics);
        adjMatrics.setLayout(adjMatricsLayout);
        adjMatricsLayout.setHorizontalGroup(
            adjMatricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adjMatricsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(ver, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adjMatricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adjMatricsLayout.createSequentialGroup()
                        .addComponent(AddV)
                        .addGap(42, 42, 42)
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        adjMatricsLayout.setVerticalGroup(
            adjMatricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adjMatricsLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(adjMatricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddV)
                    .addComponent(ver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        adjMatrics.setLayer(end, javax.swing.JLayeredPane.DEFAULT_LAYER);
        adjMatrics.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        adjMatrics.setLayer(AddE, javax.swing.JLayeredPane.DEFAULT_LAYER);
        adjMatrics.setLayer(ver, javax.swing.JLayeredPane.DEFAULT_LAYER);
        adjMatrics.setLayer(AddV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        adjMatrics.setLayer(start, javax.swing.JLayeredPane.DEFAULT_LAYER);

        adjMa.setText("Adjancy Matrix");
        adjMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adjMaActionPerformed(evt);
            }
        });

        bfs.setText("Breadth-First Search");
        bfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfsActionPerformed(evt);
            }
        });

        dfs.setText("Depth-First Search");
        dfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dfsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dfs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adjMa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bfs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(adjMa)
                .addGap(66, 66, 66)
                .addComponent(dfs)
                .addGap(76, 76, 76)
                .addComponent(bfs)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(adjMa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bfs, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(dfs, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
            .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bFS))
            .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(adjMatrics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
            .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dFS))
            .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPane1)
                    .addContainerGap()))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
            .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bFS))
            .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(adjMatrics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
            .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dFS))
            .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPane1)
                    .addContainerGap()))
        );
        Main.setLayer(bFS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Main.setLayer(dFS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Main.setLayer(adjMatrics, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Main.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dfsActionPerformed
        jLayeredPane1.setVisible(false);
        adjMatrics.setVisible(false);
        dFS.setVisible(true);
        bFS.setVisible(false);
    }//GEN-LAST:event_dfsActionPerformed

    private void bfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfsActionPerformed
        jLayeredPane1.setVisible(false);
        adjMatrics.setVisible(false);
        bFS.setVisible(true);
        dFS.setVisible(false);


    }//GEN-LAST:event_bfsActionPerformed

    private void adjMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adjMaActionPerformed
        jLayeredPane1.setVisible(false);
        adjMatrics.setVisible(true);
        dFS.setVisible(false);
        bFS.setVisible(false);

    }//GEN-LAST:event_adjMaActionPerformed

    public void dFsBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dFsBTActionPerformed
try{
        doo = (Graphics2D) jPanel2.getGraphics();
        df.dfs();

        doo.setFont(new Font("TimesRoman", Font.BOLD, 19));
        doo.clearRect(0, 0, getWidth(), getHeight());
        doo.drawString("Visits: " + df.out, 5, 25);
        df.out = "";
}
catch(Exception e){
JOptionPane.showMessageDialog(null, "There is no vertices yet to search");
}
    }//GEN-LAST:event_dFsBTActionPerformed

    public void AddE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddE1ActionPerformed
try{
        String j = start1.getText();
        int k = Integer.parseInt(j) - 1;
        String c = end1.getText();
        int v = Integer.parseInt(c) - 1;
        d = (Graphics2D) display.getGraphics();
        df.addEdge(k, v);
        if (k != v) {
            d.setFont(new Font("TimesRoman", Font.BOLD, 17));
            d.drawLine(x[k] + 30, y[k] + 20, x[v], y[v] + 19);
        } else {
        }
}
catch(Exception e){
JOptionPane.showMessageDialog(null, "Enter an edge");
}
    }//GEN-LAST:event_AddE1ActionPerformed

    public void AddV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddV1ActionPerformed
try{
        String f = ver1.getText();
        String toUpperCase = f.toUpperCase();
        char r = toUpperCase.charAt(0);
        df.addVertex(r);
        int radius = 30;
        int gap = 0;
        int R = (int) (Math.random() * 256);
        int G = (int) (Math.random() * 256);
        int B = (int) (Math.random() * 256);
        x[i] = R % 320 + gap;
        y[i] = B % 167 + gap;
        d = (Graphics2D) display.getGraphics();
        d.setColor(new Color(R, G, B));
        d.setFont(new Font("TimesRoman", Font.BOLD, 15));
        d.drawOval(x[i], y[i], radius, radius);
        d.fillOval(x[i], y[i], radius, radius);
        d.setColor(Color.BLACK);
        d.drawString(r + "", x[i] + 10, y[i] + 20);

        i++;
        gap += 30;
}
catch(Exception e){
JOptionPane.showMessageDialog(null, "Enter a vertex");
}
    }//GEN-LAST:event_AddV1ActionPerformed

    private void AddVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVActionPerformed
        try {
            String x = ver.getText();
            String toUpperCase = x.toUpperCase();
            char y = toUpperCase.charAt(0);
            m.addVertex(y);
            String out = "" + ("\n");
            for (int j = 0; j < m.nVerts; j++) {
                out += ("\n");
                out += m.vertexList[j].label + "  ";

                for (int k = 0; k < m.nVerts; k++) {
                    out += (String.valueOf(m.adjMat[j][k])) + "  ";
                }
                out += ("\n");
            }
            Display.setText(m.displayVer());
            Display.setText(Display.getText() + out);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter a vertex");
        }
    }//GEN-LAST:event_AddVActionPerformed

    private void AddEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEActionPerformed
        try {
            String x = start.getText();
            int l = Integer.parseInt(x);
            String c = end.getText();
            int v = Integer.parseInt(c);

            m.addEdge(l - 1, v - 1);
            String out = "" + ("\n");

            for (int j = 0; j < m.nVerts; j++) {
                out += ("\n");
                out += m.vertexList[j].label + "  ";
                for (int k = 0; k < m.nVerts; k++) {
                    out += (String.valueOf(m.adjMat[j][k])) + "  ";
                }
                out += ("\n");
            }
            Display.setText(m.displayVer());
            Display.setText(Display.getText() + out);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter an edge");
        }
    }//GEN-LAST:event_AddEActionPerformed

    private void AddV2BsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddV2BsActionPerformed
try{
        String f = ver2bs.getText();
        String toUpperCase = f.toUpperCase();
        char r = toUpperCase.charAt(0);
        bf.addVertex(r);
        int radius = 30;
        int R = (int) (Math.random() * 256);
        int G = (int) (Math.random() * 256);
        int B = (int) (Math.random() * 256);
        int gap = 0;
        xB[iB] = R % 320 + gap;
        yB[iB] = B % 167 + gap;
        dB = (Graphics2D) display1Bs.getGraphics();
        dB.setColor(new Color(R, G, B));
        dB.setFont(new Font("TimesRoman", Font.BOLD, 15));
        dB.drawOval(xB[iB], yB[iB], radius, radius);
        dB.fillOval(xB[iB], yB[iB], radius, radius);
        dB.setColor(Color.BLACK);
        dB.drawString(r + "", xB[iB] + 10, yB[iB] + 20);

        iB++;
        gap += 30;
}
catch(Exception e){
JOptionPane.showMessageDialog(null, "Enter a vertex");
}
    }//GEN-LAST:event_AddV2BsActionPerformed

    private void AddE2BsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddE2BsActionPerformed
try{
        String j = start2Bs.getText();
        int k = Integer.parseInt(j) - 1;
        String c = end2Bs.getText();
        int v = Integer.parseInt(c) - 1;
        dB = (Graphics2D) display1Bs.getGraphics();
        bf.addEdge(k, v);
        if (k != v) {
            dB.setFont(new Font("TimesRoman", Font.BOLD, 17));
            dB.drawLine(xB[k] + 30, yB[k] + 20, xB[v], yB[v] + 19);
        } else {
        }
}
catch(Exception e){
JOptionPane.showMessageDialog(null, "Enter an edge");
}
    }//GEN-LAST:event_AddE2BsActionPerformed

    private void bfsBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfsBTActionPerformed
        try{
        dooB = (Graphics2D) jPanel3.getGraphics();
        bf.bfs();
        dooB.setFont(new Font("TimesRoman", Font.BOLD, 19));
        dooB.clearRect(0, 0, getWidth(), getHeight());
        dooB.drawString("Visits: " + bf.out, 5, 25);
        bf.out = "";
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "There is no vertices yet to search");
        }
    }//GEN-LAST:event_bfsBTActionPerformed
    public void setlookAndFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GraphGui().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddE;
    private javax.swing.JButton AddE1;
    private javax.swing.JButton AddE2Bs;
    private javax.swing.JButton AddV;
    private javax.swing.JButton AddV1;
    private javax.swing.JButton AddV2Bs;
    private javax.swing.JTextArea Display;
    public javax.swing.JLayeredPane Main;
    private javax.swing.JButton adjMa;
    public javax.swing.JLayeredPane adjMatrics;
    public javax.swing.JLayeredPane bFS;
    private javax.swing.JButton bfs;
    private javax.swing.JButton bfsBT;
    public javax.swing.JLayeredPane dFS;
    private javax.swing.JButton dFsBT;
    public javax.swing.JButton dfs;
    public javax.swing.JPanel display;
    public javax.swing.JPanel display1Bs;
    private javax.swing.JTextField end;
    private javax.swing.JTextField end1;
    private javax.swing.JTextField end2Bs;
    public javax.swing.JLayeredPane jLayeredPane1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField start;
    private javax.swing.JTextField start1;
    private javax.swing.JTextField start2Bs;
    private javax.swing.JTextField ver;
    private javax.swing.JTextField ver1;
    private javax.swing.JTextField ver2bs;
    // End of variables declaration//GEN-END:variables
}
