/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Queue;

import java.awt.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Mahmoud
 */
public class QueueGui extends javax.swing.JFrame {

    Queue q = new Queue(20);
    CQueue cq = new CQueue(9);
    Graphics2D gh;

//    public void paint(Graphics2D gh) {
//        super.paintComponents(gh);
//
//        gh.drawLine(73, 140, 30, 120);
//        gh.drawLine(73, 112, 30, 212);
//       // g.drawRect(17, 130, 325, 200);
//
//    }
    /**
     * Creates new form QueueGui
     */
    public QueueGui() {
        setLookAndFeel();
        initComponents();
        setLocationRelativeTo(null);
        QueueTOBT.doClick();
        gh = (Graphics2D) jPanel1.getGraphics();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        QueueTOBT = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        CQueTOBT = new javax.swing.JToggleButton();
        ObSelec = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rearPos = new javax.swing.JLabel();
        InsertBt = new javax.swing.JButton();
        RemoveBT = new javax.swing.JButton();
        DisplayArea = new javax.swing.JLabel();
        FrontPos = new javax.swing.JLabel();
        Num = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        QueueTOBT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        QueueTOBT.setText("Queue");
        QueueTOBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueueTOBTActionPerformed(evt);
            }
        });

        jLabel4.setText("Select :");

        CQueTOBT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CQueTOBT.setText("Circular Queue");
        CQueTOBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CQueTOBTActionPerformed(evt);
            }
        });

        ObSelec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Integer", "String", "Integer and Strings" }));
        ObSelec.setSelectedItem(null);
        ObSelec.setName(""); // NOI18N
        ObSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObSelecActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Chosee :");

        jLabel6.setText("OR");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setOpaque(false);

        InsertBt.setText("Enqueue");
        InsertBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBtActionPerformed(evt);
            }
        });

        RemoveBT.setText("Dequeue");
        RemoveBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBTActionPerformed(evt);
            }
        });

        DisplayArea.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        Num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumActionPerformed(evt);
            }
        });

        jLabel3.setText("Rear is now :");

        jLabel1.setText("Enter");

        jLabel2.setText("Front is now :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DisplayArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rearPos, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                    .addComponent(FrontPos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RemoveBT))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Num, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InsertBt)
                        .addGap(72, 72, 72)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertBt)
                    .addComponent(jLabel1)
                    .addComponent(Num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(DisplayArea, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FrontPos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rearPos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(RemoveBT, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(QueueTOBT)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(121, 121, 121)))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CQueTOBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ObSelec, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ObSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CQueTOBT)
                    .addComponent(QueueTOBT)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        jLayeredPane1.setLayer(QueueTOBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(CQueTOBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ObSelec, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBtActionPerformed
        if (QueueTOBT.isSelected()) {
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(0)) {
                try {
                    String x = Num.getText();
                    int y = Integer.parseInt(x);
                    Data d = new Data(y);
                    q.insert(d);

                    DisplayArea.setText(q.toString());
                    Num.setText(null);
                    Name.setText(null);
                    FrontPos.setText(q.getFrontElement());
                    rearPos.setText(q.getRearElement());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Please Enter a Number !");
                }
            }
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(1)) {
                String y = Name.getText();
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a Name");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y);
                    q.insert(d);
                }
                DisplayArea.setText(q.toString());
                Num.setText(null);
                Name.setText(null);
                FrontPos.setText(q.getFrontElement());
                rearPos.setText(q.getRearElement());

            }

            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(2)) {
                String y = Name.getText();
                String x = Num.getText();
                int m = Integer.parseInt(x);
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a correct Name and ID");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y, m);
                    q.insert(d);
                }
                DisplayArea.setText(q.toString());
                Num.setText(null);
                Name.setText(null);
                FrontPos.setText(q.getFrontElement());
                rearPos.setText(q.getRearElement());

            }

        }

        if (CQueTOBT.isSelected()) {
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(0)) {
                try {
                    String x = Num.getText();
                    int y = Integer.parseInt(x);
                    Data d = new Data(y);
                    cq.insert(d);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Please Enter a Number !");
                }
            }
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(1)) {
                String y = Name.getText();
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a Name");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y);
                    cq.insert(d);
                }

            }

            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(2)) {
                String y = Name.getText();
                String x = Num.getText();
                int m = Integer.parseInt(x);
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a correct Name and ID");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y, m);
                    cq.insert(d);
                }

            }

            DisplayArea.setText(cq.toString());
            Num.setText(null);
            Name.setText(null);
            FrontPos.setText(cq.getFrontElement());
            rearPos.setText(cq.getRearElement());
        }
       
        
    }//GEN-LAST:event_InsertBtActionPerformed

    private void RemoveBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBTActionPerformed
        if (QueueTOBT.isSelected()) {
            if (q.isEmpty()) {

                DisplayArea.setText(null);
                JOptionPane.showMessageDialog(null, "Queue is already Empty");
            }
            q.remove();

            if (!q.isEmpty()) {
                DisplayArea.setText(q.toString());
                FrontPos.setText(q.q[(q.front + 1) % q.q.length].display());
                rearPos.setText(q.q[q.rear].display());
            }
            if (q.isEmpty()) {

                DisplayArea.setText(q.toString());
                FrontPos.setText(null);
                rearPos.setText(null);
            }

        }
        if (CQueTOBT.isSelected()) {
            if (cq.elemnts == 0) {
                DisplayArea.setText(null);
                JOptionPane.showMessageDialog(null, "Circular Queue is already Empty");
            }

            cq.remove();
            if (!cq.isEmpty()) {
                DisplayArea.setText(cq.toString());
                FrontPos.setText(cq.getFrontElement());
                rearPos.setText(cq.getRearElement());
            }
            if (cq.isEmpty()) {

                DisplayArea.setText(cq.toString());
                FrontPos.setText(null);
                rearPos.setText(null);
            }

        }
        
    }//GEN-LAST:event_RemoveBTActionPerformed

    private void QueueTOBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueueTOBTActionPerformed

        if (QueueTOBT.isSelected()) {

            QueueTOBT.setEnabled(false);
            CQueTOBT.setEnabled(true);
            CQueTOBT.setSelected(false);
            DisplayArea.setText(null);
        }
    }//GEN-LAST:event_QueueTOBTActionPerformed

    private void CQueTOBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CQueTOBTActionPerformed

        if (CQueTOBT.isSelected()) {

            CQueTOBT.setEnabled(false);
            QueueTOBT.setEnabled(true);
            QueueTOBT.setSelected(false);
            DisplayArea.setText(null);
        }
    }//GEN-LAST:event_CQueTOBTActionPerformed

    private void ObSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObSelecActionPerformed
        if (ObSelec.getSelectedItem() == ObSelec.getItemAt(0)) {

            Name.setEnabled(false);
            Num.setEnabled(true);
            q.clear();
            cq.clear();
            DisplayArea.setText(null);
        }
        if (ObSelec.getSelectedItem() == ObSelec.getItemAt(1)) {
            q.clear();
            cq.clear();
            Num.setEnabled(false);
            Name.setEnabled(true);

            DisplayArea.setText(null);
        }
        if (ObSelec.getSelectedItem() == ObSelec.getItemAt(2)) {
            q.clear();
            cq.clear();
            Num.setEnabled(true);
            Name.setEnabled(true);

            DisplayArea.setText(null);
        }
    }//GEN-LAST:event_ObSelecActionPerformed

    private void NumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumActionPerformed

    public void setLookAndFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueueGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QueueGui().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CQueTOBT;
    private javax.swing.JLabel DisplayArea;
    private javax.swing.JLabel FrontPos;
    private javax.swing.JButton InsertBt;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Num;
    private javax.swing.JComboBox ObSelec;
    private javax.swing.JToggleButton QueueTOBT;
    private javax.swing.JButton RemoveBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLayeredPane jLayeredPane1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JLabel rearPos;
    // End of variables declaration//GEN-END:variables
}
