/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Array;

import javax.swing.JOptionPane;

/**
 *
 * @author Mahmoud
 */
public class Array extends javax.swing.JFrame {

    /**
     * Creates new form Array
     */
    UnorderArray arr = new UnorderArray(60);
    OrderArray Oarr = new OrderArray(15);

    public Array() {
        setLookAndFeel();
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        DeleteBT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NUm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Display = new javax.swing.JLabel();
        UnOrdArrBT = new javax.swing.JToggleButton();
        RemoveF = new javax.swing.JTextField();
        InsertBT = new javax.swing.JButton();
        OrdArrBT = new javax.swing.JToggleButton();
        search = new javax.swing.JButton();
        ObSelec = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DeleteBT.setText("Remove");
        DeleteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBTActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter  :");

        jLabel3.setText("Please Select :");

        jLabel2.setText("Index Number :");

        Display.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        UnOrdArrBT.setText("Unordered Array");
        UnOrdArrBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnOrdArrBTActionPerformed(evt);
            }
        });

        InsertBT.setText("Insert");
        InsertBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBTActionPerformed(evt);
            }
        });

        OrdArrBT.setText("Ordered Array");
        OrdArrBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdArrBTActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        ObSelec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Integer", "String", "Integer and String" }));
        ObSelec.setSelectedItem(null);
        ObSelec.setName(""); // NOI18N
        ObSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObSelecActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Chosee ");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(13, 13, 13)
                                .addComponent(UnOrdArrBT)
                                .addGap(18, 18, 18)
                                .addComponent(OrdArrBT))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ObSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(InsertBT, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(search)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RemoveF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteBT)
                        .addGap(56, 56, 56))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)
                                .addComponent(NUm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(62, Short.MAX_VALUE))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ObSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(43, 43, 43)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnOrdArrBT)
                    .addComponent(OrdArrBT)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertBT)
                    .addComponent(NUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(search)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RemoveF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBT))
                .addContainerGap())
        );
        jLayeredPane1.setLayer(DeleteBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(NUm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Display, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(UnOrdArrBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(RemoveF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(InsertBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(OrdArrBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(search, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ObSelec, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Name, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBTActionPerformed
        if (UnOrdArrBT.isSelected()) {

            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(0)) {
                String y = NUm.getText();
                int x = Integer.parseInt(y);
                Data d = new Data(x);
                arr.insert(d);

                Display.setText(arr.toString());

            }
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(1)) {
                String y = Name.getText();
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a Name");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y);
                    arr.insert(d);
                    Display.setText(arr.toString());

                }
            }
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(2)) {
                String y = Name.getText();
                String x = NUm.getText();
                int m = Integer.parseInt(x);
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a correct Name and ID");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y, m);
                    arr.insert(d);
                    Display.setText(arr.toString());
                }
            }
        }
        if (OrdArrBT.isSelected()) {

            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(0)) {
                String y = NUm.getText();
                int x = Integer.parseInt(y);
                Data d = new Data(x);
                Oarr.insert(d);

                Display.setText(Oarr.toString());

            }
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(1)) {
                String y = Name.getText();
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a Name");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y);
                    Oarr.insert(d);
                    Display.setText(Oarr.toString());

                }
            }
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(2)) {
                String y = Name.getText();
                String x = NUm.getText();
                int m = Integer.parseInt(x);
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a correct Name and ID");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y, m);
                    Oarr.insert(d);
                    Display.setText(Oarr.toString());
                }
            }

        }

        if (!OrdArrBT.isSelected() && !UnOrdArrBT.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please select a type to begin ");

        }
    }//GEN-LAST:event_InsertBTActionPerformed

    private void DeleteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBTActionPerformed
        if (UnOrdArrBT.isSelected()) {
            try {
                if (!arr.isEmpty()) {
                    String s = RemoveF.getText();
                    int y = Integer.parseInt(s);
                    arr.remove(y);
                    Display.setText(arr.toString());
                    RemoveF.setText(null);
                } else if (arr.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Array is already Empty");
                    RemoveF.setText(null);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Please Enter a correct Index number");
                RemoveF.setText(null);
            }
        }
        if (OrdArrBT.isSelected()) {
            try {
                if (!Oarr.isEmpty()) {
                    String s = RemoveF.getText();
                    int y = Integer.parseInt(s);
                    Oarr.remove(y);
                    Display.setText(Oarr.toString());
                    RemoveF.setText(null);
                } else if (Oarr.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Array is already Empty");
                    RemoveF.setText(null);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Please Enter a correct Index number");
                RemoveF.setText(null);
            }
        }
        

    }//GEN-LAST:event_DeleteBTActionPerformed

    private void UnOrdArrBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnOrdArrBTActionPerformed

        if (UnOrdArrBT.isSelected()) {

            OrdArrBT.setSelected(false);
            Display.setText(null);
        }

    }//GEN-LAST:event_UnOrdArrBTActionPerformed

    private void OrdArrBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdArrBTActionPerformed

        if (OrdArrBT.isSelected()) {

            UnOrdArrBT.setSelected(false);
            Display.setText(null);
        }

    }//GEN-LAST:event_OrdArrBTActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
     if (UnOrdArrBT.isSelected())   {
        try {
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(0)) {
                String y = NUm.getText();
                int x = Integer.parseInt(y);
                Data d = new Data(x);
                arr.find(d);
            }
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(1)) {
                String y = Name.getText();
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a Name");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y);
                    arr.find(d);
                }
            }
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(2)) {
                String y = Name.getText();
                String x = NUm.getText();
                int m = Integer.parseInt(x);
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a correct Name and ID");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y, m);
                    arr.find(d);
                }
            }
            NUm.setText(null);
            Name.setText(null);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "you should give me some thing first to look for");
        }
        }
        
     if (OrdArrBT.isSelected())   {
        try {
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(0)) {
                String y = NUm.getText();
                int x = Integer.parseInt(y);
                Data d = new Data(x);
                Oarr.find(d);
            }
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(1)) {
                String y = Name.getText();
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a Name");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y);
                    Oarr.find(d);
                }
            }
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(2)) {
                String y = Name.getText();
                String x = NUm.getText();
                int m = Integer.parseInt(x);
                try {
                    int l = Integer.parseInt(y);
                    JOptionPane.showMessageDialog(null, "Please Enter a correct Name and ID");
                } catch (NumberFormatException ex) {
                    Data d = new Data(y, m);
                    Oarr.find(d);
                }
            }
            NUm.setText(null);
            Name.setText(null);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "you should give me some thing first to look for");
        }
        }
    }//GEN-LAST:event_searchActionPerformed

    private void ObSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObSelecActionPerformed
        if (ObSelec.getSelectedItem() == ObSelec.getItemAt(0)) {

            Name.setEnabled(false);
            NUm.setEnabled(true);
            Oarr.clear();
            arr.clear();
            Display.setText(null);
        }
        if (ObSelec.getSelectedItem() == ObSelec.getItemAt(1)) {

            NUm.setEnabled(false);
            Name.setEnabled(true);
            Oarr.clear();
            arr.clear();
            Display.setText(null);
        }
        if (ObSelec.getSelectedItem() == ObSelec.getItemAt(2)) {

            NUm.setEnabled(true);
            Name.setEnabled(true);
            Oarr.clear();
            arr.clear();
            Display.setText(null);
        }
    }//GEN-LAST:event_ObSelecActionPerformed

    private void setLookAndFeel() {
        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;
                }

            }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Array.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Array().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBT;
    private javax.swing.JLabel Display;
    private javax.swing.JButton InsertBT;
    private javax.swing.JTextField NUm;
    private javax.swing.JTextField Name;
    private javax.swing.JComboBox ObSelec;
    private javax.swing.JToggleButton OrdArrBT;
    private javax.swing.JTextField RemoveF;
    private javax.swing.JToggleButton UnOrdArrBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
