package stack5;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Student
 */
public class GUIStack extends javax.swing.JFrame {

    Stack k = new Stack(20);

    /**
     * Creates new form GUIStack
     */
    public GUIStack() {
        setlookAndFell();

        initComponents();
        StackLayer.setVisible(true);
        AppLayer.setVisible(false);
        setResizable(false);
        setLocationRelativeTo(null);

        setTitle("Stack");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sourceLayer = new javax.swing.JLayeredPane();
        AppLayer = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRW = new javax.swing.JTextField();
        InsertRW = new javax.swing.JButton();
        DisplayRW = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        checkBT = new javax.swing.JButton();
        ch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DisplayD = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        iOp = new javax.swing.JTextField();
        transform = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        displatran = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        postNo = new javax.swing.JTextField();
        result = new javax.swing.JButton();
        postnores = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        StackLayer = new javax.swing.JLayeredPane();
        NUm = new javax.swing.JTextField();
        PopBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayF = new javax.swing.JTextArea();
        PushBT = new javax.swing.JButton();
        PeekBt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        StackAppBT = new javax.swing.JButton();
        ObSelec = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Reverse a word", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe Print", 0, 11))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel2.setText("Enter a word :");

        txtRW.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        InsertRW.setText("Insert");
        InsertRW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertRWActionPerformed(evt);
            }
        });

        DisplayRW.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DisplayRW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setText("Reversed :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(DisplayRW, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtRW, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(InsertRW)))
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertRW))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addComponent(DisplayRW, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Delimiter Matching", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe Print", 0, 11))); // NOI18N
        jPanel2.setOpaque(false);

        checkBT.setText("Check");
        checkBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBTActionPerformed(evt);
            }
        });

        ch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setText("Enter :");

        DisplayD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DisplayD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(DisplayD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)
                        .addComponent(ch, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(checkBT)
                        .addGap(51, 51, 51))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBT)
                    .addComponent(ch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DisplayD, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Transforming Infix to Postfix", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe Print", 0, 11))); // NOI18N
        jPanel3.setOpaque(false);

        jLabel6.setText("Enter Infix :");

        iOp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        transform.setText("Transform");
        transform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformActionPerformed(evt);
            }
        });

        jLabel7.setText("Postfix :");

        displatran.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(displatran, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(iOp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(transform)
                        .addGap(58, 58, 58))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(iOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transform))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displatran, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Evaluating Postfix Notation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 11))); // NOI18N
        jPanel4.setOpaque(false);

        jLabel8.setText("Enter Postfix :");

        postNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        result.setText("Result");
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });

        postnores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setText("Result :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(postnores, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(postNo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(result)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(postNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(result))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(postnores, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout AppLayerLayout = new javax.swing.GroupLayout(AppLayer);
        AppLayer.setLayout(AppLayerLayout);
        AppLayerLayout.setHorizontalGroup(
            AppLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppLayerLayout.createSequentialGroup()
                .addGroup(AppLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 52, Short.MAX_VALUE))
        );
        AppLayerLayout.setVerticalGroup(
            AppLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppLayerLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        AppLayer.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AppLayer.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AppLayer.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AppLayer.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        StackLayer.setBackground(java.awt.SystemColor.textText);

        PopBt.setText("Pop");
        PopBt.setOpaque(false);
        PopBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopBtActionPerformed(evt);
            }
        });

        DisplayF.setEditable(false);
        DisplayF.setColumns(20);
        DisplayF.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        DisplayF.setRows(5);
        DisplayF.setToolTipText("");
        DisplayF.setBorder(null);
        DisplayF.setOpaque(false);
        jScrollPane1.setViewportView(DisplayF);

        PushBT.setText("Push");
        PushBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PushBTActionPerformed(evt);
            }
        });

        PeekBt.setText("Peek");
        PeekBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeekBtActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter :");

        StackAppBT.setText("Stack Applications");
        StackAppBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StackAppBTActionPerformed(evt);
            }
        });

        ObSelec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Integer", "String", "Integer and String" }));
        ObSelec.setSelectedItem(null);
        ObSelec.setName(""); // NOI18N
        ObSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObSelecActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Chosee :");

        javax.swing.GroupLayout StackLayerLayout = new javax.swing.GroupLayout(StackLayer);
        StackLayer.setLayout(StackLayerLayout);
        StackLayerLayout.setHorizontalGroup(
            StackLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StackLayerLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(StackLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(StackLayerLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ObSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StackLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(StackLayerLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(NUm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PushBT)))
                    .addComponent(StackAppBT))
                .addGap(18, 18, 18)
                .addGroup(StackLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PopBt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeekBt))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        StackLayerLayout.setVerticalGroup(
            StackLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StackLayerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StackLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StackLayerLayout.createSequentialGroup()
                        .addGroup(StackLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ObSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(38, 38, 38)
                        .addGroup(StackLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(NUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PushBT)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(StackAppBT))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StackLayerLayout.createSequentialGroup()
                        .addComponent(PopBt)
                        .addGap(45, 45, 45)
                        .addComponent(PeekBt)
                        .addGap(91, 91, 91)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        StackLayer.setLayer(NUm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StackLayer.setLayer(PopBt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StackLayer.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StackLayer.setLayer(PushBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StackLayer.setLayer(PeekBt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StackLayer.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StackLayer.setLayer(StackAppBT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StackLayer.setLayer(ObSelec, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StackLayer.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StackLayer.setLayer(Name, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout sourceLayerLayout = new javax.swing.GroupLayout(sourceLayer);
        sourceLayer.setLayout(sourceLayerLayout);
        sourceLayerLayout.setHorizontalGroup(
            sourceLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
            .addGroup(sourceLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AppLayer, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(sourceLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(StackLayer, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        sourceLayerLayout.setVerticalGroup(
            sourceLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
            .addGroup(sourceLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AppLayer))
            .addGroup(sourceLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(StackLayer, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        sourceLayer.setLayer(AppLayer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sourceLayer.setLayer(StackLayer, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sourceLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sourceLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PeekBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeekBtActionPerformed
        try {
            JOptionPane.showMessageDialog(null, "Last Elemnt is " + k.stackArray[k.top].display(), null, JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Stack is already empty ,there is no elemnts to show", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_PeekBtActionPerformed

    private void PushBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PushBTActionPerformed
        if (ObSelec.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Select the Desired data type first");
        }
        try {
            if (ObSelec.getSelectedItem() == ObSelec.getItemAt(0)) {
                String y = NUm.getText();
                int x = Integer.parseInt(y);
                Data d = new Data(x);
                k.push(d);
            }
             if (ObSelec.getSelectedItem() == ObSelec.getItemAt(1)) {
                    String y = Name.getText();
                    try {
                        int l = Integer.parseInt(y);
                        JOptionPane.showMessageDialog(null, "Please Enter a Name");
                    } catch (NumberFormatException ex) {
                        Data d = new Data(y);
                        k.push(d);
                    }
             }
              if (ObSelec.getSelectedItem() == ObSelec.getItemAt(2)) {
                    String y = Name.getText();
                    String x = NUm.getText();
                    int m = Integer.parseInt(x);
                    try {
                        int l = Integer.parseInt(y);
                        JOptionPane.showMessageDialog(null, "Please Enter a correct Name and ID");
                    } catch (NumberFormatException ex) {
                        Data d = new Data(y, m);
                        k.push(d);
                    }
              }
            
            DisplayF.setText(null);
            for (int i = 0; i <= k.top - 1; i++) {
                DisplayF.setText(k.stackArray[i].display() + "\n" + DisplayF.getText());
            }
           DisplayF.setText(k.stackArray[k.top].display() + "    <--- Top \n" + DisplayF.getText());
            NUm.setText(null);
            Name.setText(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please Enter a value in box");
        }

    }//GEN-LAST:event_PushBTActionPerformed

    private void PopBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopBtActionPerformed

        try {

            k.pop();
            DisplayF.setText(null);

            for (int i = 0; i < k.top; i++) {
                DisplayF.setText(k.stackArray[i].display() + "\n" + DisplayF.getText());
            }
            if (k.top > -1) {
                DisplayF.setText(k.stackArray[k.top].display() + " <--- Top" + "\n" + DisplayF.getText());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Stack is already empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_PopBtActionPerformed

    private void StackAppBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StackAppBTActionPerformed
        StackLayer.setVisible(false);
        AppLayer.setVisible(true);

    }//GEN-LAST:event_StackAppBTActionPerformed

    private void InsertRWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertRWActionPerformed
        String L = txtRW.getText();

        reverse r = new reverse(L);
        r.insert(L);
        r.display();
        DisplayRW.setText(r.out);

    }//GEN-LAST:event_InsertRWActionPerformed

    private void ObSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObSelecActionPerformed
        if (ObSelec.getSelectedItem() == ObSelec.getItemAt(0)) {

            Name.setEnabled(false);
            NUm.setEnabled(true);
            k.clear();
            DisplayF.setText(null);
        }
        if (ObSelec.getSelectedItem() == ObSelec.getItemAt(1)) {

            NUm.setEnabled(false);
            Name.setEnabled(true);
            k.clear();
            DisplayF.setText(null);
        }
        if (ObSelec.getSelectedItem() == ObSelec.getItemAt(2)) {

            NUm.setEnabled(true);
            Name.setEnabled(true);
            k.clear();
            DisplayF.setText(null);
        }
    }//GEN-LAST:event_ObSelecActionPerformed

    private void checkBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBTActionPerformed
       DelimiterMatching d=new DelimiterMatching();
       String x= ch.getText();
       d.isTrue(x);
       DisplayD.setText(d.out);
    }//GEN-LAST:event_checkBTActionPerformed

    private void transformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transformActionPerformed
       String x=iOp.getText();
       Iop i=new Iop(x);
       i.doTrans();
       displatran.setText(i.output);
    }//GEN-LAST:event_transformActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        String x= postNo.getText();
        ParsePost p=new ParsePost(x);
        postnores.setText(p.doParse());
    }//GEN-LAST:event_resultActionPerformed

    public final void setlookAndFell() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIStack().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLayeredPane AppLayer;
    private javax.swing.JLabel DisplayD;
    private javax.swing.JTextArea DisplayF;
    private javax.swing.JLabel DisplayRW;
    private javax.swing.JButton InsertRW;
    private javax.swing.JTextField NUm;
    private javax.swing.JTextField Name;
    private javax.swing.JComboBox ObSelec;
    private javax.swing.JButton PeekBt;
    private javax.swing.JButton PopBt;
    private javax.swing.JButton PushBT;
    public javax.swing.JButton StackAppBT;
    public javax.swing.JLayeredPane StackLayer;
    private javax.swing.JTextField ch;
    private javax.swing.JButton checkBT;
    private javax.swing.JLabel displatran;
    private javax.swing.JTextField iOp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField postNo;
    private javax.swing.JLabel postnores;
    private javax.swing.JButton result;
    public javax.swing.JLayeredPane sourceLayer;
    private javax.swing.JButton transform;
    private javax.swing.JTextField txtRW;
    // End of variables declaration//GEN-END:variables
}
